enum AppLanguage { en, hi, mr }

class AppStrings {
  static const Map<AppLanguage, Map<String, String>> _v = {
    AppLanguage.en: {
      'lang_label': 'EN',
      'dashboard': 'Dashboard',
      'integrations': 'Integrations',
      'features': 'Benefits',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'settings': 'Settings',
      'withdrawal_history': 'Withdrawal History',
      'payment_settings': 'Payment Settings',
      'help_support': 'Help & Support',
      'insured': 'Insured',
      'not_insured': 'Not Insured',
      'get_gigbit_insurance': 'Get GigBit Insurance',
      'insurance_opt_in_title': 'Enable GigBit Insurance?',
      'insurance_opt_in_body':
          'GigBit Insurance charges Rs 75 every month. It will be auto-deducted on the 1st day of each month, and insurance benefits will be enabled.',
      'yes': 'Yes',
      'no': 'No',
      'logout': 'Logout',
      'done': 'Done',
      'edit': 'Edit',
      'enable_vehicle_rent': 'Enable vehicle rent',
      'wallet_balance': 'Wallet Balance',
      'total_withdrawable_balance': 'Total Withdrawable Balance',
      'withdraw_now': 'Withdraw Now',
      'withdraw_funds': 'Withdraw Funds',
      'amount': 'Amount',
      'total_earnings': 'Total Earnings',
      'total_withdrawn': 'Total Withdrawn',
      'insurance_pool': 'Insurance Pool',
      'transactions': 'Transactions',
      'trips': 'Trips',
      'platform_earnings_breakdown': 'Breakdown',
      'no_platform_data': 'No platform data yet',
      'add_transaction': 'Add Transaction',
      'platform': 'Platform',
      'save_transaction': 'Save Transaction',
      'add_expense': 'Add Expense',
      'category': 'Category',
      'save_expense': 'Save Expense',
      'platform_connections': 'Platform Connections',
      'platform_name': 'Platform name',
      'connect': 'Connect',
      'sync_amount': 'Sync amount',
      'sync_earning': 'Sync Earning',
      'total_contribution': 'Total Contribution',
      'submit_insurance_claim': 'Submit Insurance Claim',
      'description': 'Description',
      'submit_claim': 'Submit Claim',
      'recent_contributions': 'Recent Contributions',
      'eligibility_score': 'Eligibility Score',
      'recommended_limit': 'Recommended Limit',
      'loan_amount': 'Loan amount',
      'apply_loan': 'Apply Loan',
      'subscription': 'Subscription',
      'plans': 'Plans',
      'active_plan': 'Active Plan',
      'remaining': 'Remaining',
      'starter': 'Starter',
      'pro': 'Pro',
      'power': 'Power',
      'solo': 'Solo',
      'duo': 'Duo',
      'trio': 'Trio',
      'unity': 'Unity',
      'subscription_plans': 'Subscription Plans',
      'expires': 'Expires',
      'payment_method': 'Payment method',
      'upi': 'UPI',
      'card': 'Card',
      'net_banking': 'Net Banking',
      'pay_now': 'Pay Now',
      'month': 'month',
      'up_to': 'Up to',
      'platforms': 'platforms',
      'subscription_required': 'Subscription required',
      'required_to_continue': 'required to continue',
      'plan_limit_reached': 'Plan limit reached',
      'plan_slots_note':
          'You can reconnect only previously connected platforms.',
      'platform_limit': 'Platform limit',
      'logged_in_as': 'Logged in as',
      'your_information': 'Your Information',
      'other_information': 'Other Information',
      'notifications': 'Notifications',
      'legal': 'Legal',
      'faqs': 'FAQs',
      'raise_ticket': 'Raise a Ticket',
      'terms_conditions': 'Terms & Conditions',
      'accept_terms': 'I agree to Terms & Conditions',
      'accept_terms_required': 'Please accept Terms & Conditions to continue',
      'vehicle_rented': 'Vehicle rented?',
      'gigbit_insurance': 'GigBit Insurance?',
      'daily_fuel': 'Daily fuel',
      'enter_daily_fuel': 'Enter daily fuel cost',
      'rent': 'Rent',
      'enter_valid_rent': 'Enter valid rent',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'privacy_policy': 'Privacy Policy',
      'full_name': 'Full Name',
      'username': 'Username',
      'enter_full_name': 'Enter full name',
      'enter_valid_username': 'Username must be 3-24 chars (a-z, 0-9, . or _)',
      'new_password_min_8': 'Password must be at least 8 characters',
      'update_profile': 'Update Profile',
      'change_email': 'Change Email',
      'new_email': 'New Email',
      'request_change': 'Request Change',
      'change_password': 'Change Password',
      'password': 'Password',
      'old_password': 'Old Password',
      'new_password': 'New Password',
      'update_password': 'Update Password',
      'enter_valid_platform_amount': 'Enter valid platform and amount',
      'enter_valid_expense': 'Enter valid expense category and amount',
      'enter_platform_name': 'Enter a platform name',
      'enter_platform_sync_amount': 'Enter platform and sync amount',
      'enter_valid_withdrawal': 'Enter valid withdrawal amount (minimum Rs 200)',
      'claim_desc_min': 'Claim description must be at least 8 characters',
      'enter_valid_loan': 'Enter valid loan amount',
      'name_cannot_empty': 'Name cannot be empty',
      'new_email_required': 'New email is required',
      'enter_valid_passwords': 'Enter valid old/new password',
      'create_account': 'Create Account',
      'login': 'Login',
      'please_wait': 'Please wait...',
      'forgot_password': 'Forgot Password/Username',
      'registered_username': 'Registered Username',
      'need_account': 'Need an account? Register',
      'already_account': 'Already have an account? Login',
      'create_your_account': 'Create your account',
      'welcome_back': 'Welcome back',
      'secure_wallet': 'Secure Wallet\nfor Gig Workers',
      'track_earnings':
          'Track earnings, manage withdrawals, and stay financially in control.',
      'reset_password': 'Reset Password',
      'registered_email': 'Registered email',
      'cancel': 'Cancel',
      'send_otp': 'Send OTP',
      'enter_otp': 'Enter OTP',
      'update': 'Update',
      'password_updated': 'Password updated. Please login.',
      'otp_generated': 'OTP generated:',
      'otp_sent_to_email': 'OTP sent to your email.',
      'enter_valid_email': 'Enter a valid email',
      'otp_must_be_6_digits': 'OTP must be 6 digits',
      'otp_verified_continue': 'OTP verified. Continue registration.',
      'dev_mode': '(dev mode)',
      'coming_soon': 'Coming soon',
      'integrate_gig_platforms': 'Integrate Gig Platforms',
      'connect_gig_platforms': 'Connect Platforms',
      'integration_hint':
          'Enter your registered mobile number for each platform, verify OTP, then continue to dashboard.',
      'continue_dashboard': 'Continue to Dashboard',
      'verified': 'Verified',
      'connected': 'Connected',
      'registered_mobile': 'Registered mobile number',
      'mobile_hint': 'e.g. 98XXXXXXXX',
      'verify_otp': 'Verify OTP',
      'verify_one_platform': 'Verify at least one platform to continue',
      'send_otp_first': 'Send OTP first',
      'invalid_otp_for': 'Invalid OTP for',
      'verified_successfully': 'verified successfully',
      'enter_valid_mobile': 'Enter a valid registered mobile number',
      'delete_account_permanently': 'Delete Account',
      'delete_account_subtitle': 'Requires admin approval',
      'delete_account_reason': 'Why do you want to delete your account?',
      'delete_account_reason_hint': 'Select a reason',
      'delete_account_other_reason': 'Other reason',
      'delete_account_submit': 'Submit Request',
      'delete_account_submitted': 'Request submitted for admin approval',
      'reason_privacy': 'Privacy concerns',
      'reason_not_using': 'I no longer use GigBit',
      'reason_switching': 'Switching to another account/app',
      'reason_support': 'Bad experience / Support issue',
      'reason_other': 'Other',
      'tax_chatbot': 'Tax Chatbot',
      'tax_assistant': 'Tax Assistant',
      'ask_tax_question': 'Ask a tax question',
      'type_message': 'Type a message...',
      'send_message': 'Send',
      'tax_bot_greeting':
          'Hi, I answer only Tax, ITR, and GigBit platform finance questions. Ask your query.',
    },
    AppLanguage.hi: {
      'lang_label': 'हि',
      'dashboard': 'डैशबोर्ड',
      'integrations': 'इंटीग्रेशन्स',
      'features': 'लाभ',
      'profile': 'प्रोफ़ाइल',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'settings': 'सेटिंग्स',
      'withdrawal_history': 'निकासी इतिहास',
      'payment_settings': 'भुगतान सेटिंग्स',
      'help_support': 'मदद और समर्थन',
      'insured': 'बीमित',
      'not_insured': 'बीमा नहीं है',
      'get_gigbit_insurance': 'GigBit बीमा लें',
      'insurance_opt_in_title': 'GigBit बीमा चालू करें?',
      'insurance_opt_in_body':
          'GigBit बीमा में हर महीने Rs 75 शुल्क लगेगा। यह हर महीने की 1 तारीख को अपने आप कटेगा और बीमा फीचर्स चालू हो जाएंगे।',
      'yes': 'हाँ',
      'no': 'नहीं',
      'logout': 'लॉगआउट',
      'done': 'पूरा हुआ',
      'edit': 'संपादित करें',
      'enable_vehicle_rent': 'वाहन किराया सक्षम करें',
      'wallet_balance': 'वॉलेट बैलेंस',
      'total_withdrawable_balance': 'कुल निकासी योग्य बैलेंस',
      'withdraw_now': 'अभी निकासी करें',
      'withdraw_funds': 'राशि निकालें',
      'amount': 'राशि',
      'total_earnings': 'कुल कमाई',
      'total_withdrawn': 'कुल निकासी',
      'insurance_pool': 'बीमा पूल',
      'transactions': 'लेन-देन',
      'trips': 'ट्रिप्स',
      'platform_earnings_breakdown': 'ब्रेकडाउन',
      'no_platform_data': 'अभी कोई प्लेटफॉर्म डेटा नहीं है',
      'add_transaction': 'लेन-देन जोड़ें',
      'platform': 'प्लेटफ़ॉर्म',
      'save_transaction': 'सेव करें',
      'add_expense': 'खर्च जोड़ें',
      'category': 'श्रेणी',
      'save_expense': 'खर्च सेव करें',
      'platform_connections': 'प्लेटफ़ॉर्म कनेक्शन',
      'platform_name': 'प्लेटफ़ॉर्म नाम',
      'connect': 'कनेक्ट',
      'sync_amount': 'सिंक राशि',
      'sync_earning': 'कमाई सिंक',
      'total_contribution': 'कुल योगदान',
      'submit_insurance_claim': 'बीमा दावा जमा करें',
      'description': 'विवरण',
      'submit_claim': 'दावा जमा करें',
      'recent_contributions': 'हालिया योगदान',
      'eligibility_score': 'योग्यता स्कोर',
      'recommended_limit': 'अनुशंसित सीमा',
      'loan_amount': 'लोन राशि',
      'apply_loan': 'लोन आवेदन',
      'subscription': 'सब्सक्रिप्शन',
      'plans': 'प्लान',
      'active_plan': 'सक्रिय प्लान',
      'remaining': 'शेष',
      'starter': 'स्टार्टर',
      'pro': 'प्रो',
      'power': 'पावर',
      'solo': 'सोलो',
      'duo': 'डुओ',
      'trio': 'ट्रायो',
      'unity': 'यूनिटी',
      'subscription_plans': 'सब्सक्रिप्शन प्लान',
      'expires': 'समाप्ति',
      'payment_method': 'भुगतान तरीका',
      'upi': 'UPI',
      'card': 'कार्ड',
      'net_banking': 'नेट बैंकिंग',
      'pay_now': 'पे करें',
      'month': 'महीना',
      'up_to': 'तक',
      'platforms': 'प्लेटफॉर्म',
      'subscription_required': 'सब्सक्रिप्शन जरूरी है',
      'required_to_continue': 'आगे बढ़ने के लिए',
      'plan_limit_reached': 'प्लान लिमिट पूरी हो गई',
      'plan_slots_note':
          'आप केवल पहले से जुड़े प्लेटफॉर्म को ही दोबारा कनेक्ट कर सकते हैं।',
      'platform_limit': 'प्लेटफॉर्म सीमा',
      'logged_in_as': 'लॉगिन उपयोगकर्ता',
      'your_information': 'आपकी जानकारी',
      'other_information': 'अन्य जानकारी',
      'notifications': 'नोटिफिकेशन्स',
      'legal': 'कानूनी',
      'faqs': 'अक्सर पूछे जाने वाले सवाल',
      'raise_ticket': 'टिकट बनाएं',
      'terms_conditions': 'नियम और शर्तें',
      'accept_terms': 'मैं नियम और शर्तें स्वीकार करता/करती हूं',
      'accept_terms_required': 'आगे बढ़ने के लिए नियम और शर्तें स्वीकार करें',
      'vehicle_rented': 'वाहन किराये पर?',
      'gigbit_insurance': 'GigBit बीमा?',
      'daily_fuel': 'दैनिक ईंधन',
      'enter_daily_fuel': 'दैनिक ईंधन खर्च दर्ज करें',
      'rent': 'किराया',
      'enter_valid_rent': 'सही किराया दर्ज करें',
      'daily': 'दैनिक',
      'weekly': 'साप्ताहिक',
      'monthly': 'मासिक',
      'yearly': 'वार्षिक',
      'privacy_policy': 'गोपनीयता नीति',
      'full_name': 'पूरा नाम',
      'username': 'यूज़रनेम',
      'enter_full_name': 'पूरा नाम दर्ज करें',
      'enter_valid_username':
          'यूज़रनेम 3-24 अक्षर का होना चाहिए (a-z, 0-9, . या _)',
      'new_password_min_8': 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए',
      'update_profile': 'प्रोफ़ाइल अपडेट',
      'change_email': 'ईमेल बदलें',
      'new_email': 'नया ईमेल',
      'request_change': 'अनुरोध भेजें',
      'change_password': 'पासवर्ड बदलें',
      'password': 'पासवर्ड',
      'old_password': 'पुराना पासवर्ड',
      'new_password': 'नया पासवर्ड',
      'update_password': 'पासवर्ड अपडेट',
      'create_account': 'खाता बनाएं',
      'login': 'लॉगिन',
      'please_wait': 'कृपया प्रतीक्षा करें...',
      'forgot_password': 'पासवर्ड/यूज़रनेम भूल गए?',
      'registered_username': 'पंजीकृत यूज़रनेम',
      'need_account': 'खाता नहीं है? रजिस्टर करें',
      'already_account': 'पहले से खाता है? लॉगिन करें',
      'create_your_account': 'अपना खाता बनाएं',
      'welcome_back': 'फिर से स्वागत है',
      'secure_wallet': 'गिग वर्कर्स के लिए\nसुरक्षित वॉलेट',
      'track_earnings':
          'कमाई ट्रैक करें, निकासी प्रबंधित करें और वित्तीय नियंत्रण रखें।',
      'integrate_gig_platforms': 'गिग प्लेटफ़ॉर्म जोड़ें',
      'connect_gig_platforms': 'प्लेटफ़ॉर्म कनेक्ट करें',
      'integration_hint':
          'हर प्लेटफ़ॉर्म का रजिस्टर्ड मोबाइल डालें, OTP सत्यापित करें, फिर डैशबोर्ड पर जाएँ।',
      'continue_dashboard': 'डैशबोर्ड पर जारी रखें',
      'verified': 'सत्यापित',
      'connected': 'कनेक्टेड',
      'registered_mobile': 'रजिस्टर्ड मोबाइल नंबर',
      'mobile_hint': 'जैसे 98XXXXXXXX',
      'verify_otp': 'OTP सत्यापित करें',
      'send_otp': 'OTP भेजें',
      'send_otp_first': 'पहले OTP भेजें',
      'enter_otp': 'OTP दर्ज करें',
      'cancel': 'रद्द करें',
      'update': 'अपडेट',
      'reset_password': 'पासवर्ड रीसेट',
      'registered_email': 'रजिस्टर्ड ईमेल',
      'password_updated': 'पासवर्ड अपडेट हो गया। कृपया लॉगिन करें।',
      'otp_generated': 'OTP बना:',
      'otp_sent_to_email': 'OTP आपके ईमेल पर भेज दिया गया है।',
      'enter_valid_email': 'मान्य ईमेल दर्ज करें',
      'otp_must_be_6_digits': 'OTP 6 अंकों का होना चाहिए',
      'otp_verified_continue': 'OTP सत्यापित। अब रजिस्ट्रेशन पूरा करें।',
      'dev_mode': '(डेव मोड)',
      'coming_soon': 'जल्द आ रहा है',
      'tax_chatbot': 'टैक्स चैटबॉट',
      'tax_assistant': 'टैक्स सहायक',
      'ask_tax_question': 'टैक्स सवाल पूछें',
      'type_message': 'संदेश लिखें...',
      'send_message': 'भेजें',
      'tax_bot_greeting':
          'नमस्ते, मैं केवल टैक्स, ITR और GigBit प्लेटफॉर्म फाइनेंस से जुड़े सवालों का जवाब देता/देती हूं। अपना सवाल पूछें।',
      'verify_one_platform':
          'जारी रखने के लिए कम से कम एक प्लेटफ़ॉर्म सत्यापित करें',
      'invalid_otp_for': 'गलत OTP:',
      'verified_successfully': 'सफलतापूर्वक सत्यापित',
      'enter_valid_mobile': 'सही रजिस्टर्ड मोबाइल नंबर दर्ज करें',
      'delete_account_permanently': 'खाता हटाएँ',
      'delete_account_subtitle': 'एडमिन की मंज़ूरी आवश्यक',
      'delete_account_reason': 'आप अपना खाता क्यों हटाना चाहते हैं?',
      'delete_account_reason_hint': 'कारण चुनें',
      'delete_account_other_reason': 'अन्य कारण',
      'delete_account_submit': 'अनुरोध भेजें',
      'delete_account_submitted': 'अनुरोध एडमिन मंज़ूरी के लिए भेजा गया',
      'reason_privacy': 'गोपनीयता चिंता',
      'reason_not_using': 'अब GigBit का उपयोग नहीं करता/करती',
      'reason_switching': 'दूसरे ऐप/अकाउंट पर जा रहा/रही हूँ',
      'reason_support': 'खराब अनुभव / सपोर्ट समस्या',
      'reason_other': 'अन्य',
    },
    AppLanguage.mr: {
      'tax_chatbot': 'टॅक्स चॅटबॉट',
      'tax_assistant': 'टॅक्स सहाय्यक',
      'ask_tax_question': 'टॅक्स प्रश्न विचारा',
      'type_message': 'मेसिज टाइप करा...',
      'send_message': 'पाठवा',
      'tax_bot_greeting':
          'नमस्कार, मी फक्त टॅक्स, ITR आणि GigBit प्लॅटफॉर्म फायनान्स प्रश्नांची उत्तरे देतो/देते. तुमचा प्रश्न विचारा.',
      'lang_label': 'मरा',
      'dashboard': 'डॅशबोर्ड',
      'integrations': 'इंटिग्रेशन्स',
      'features': 'फायदे',
      'profile': 'प्रोफाइल',
      'edit_profile': 'प्रोफाइल संपादित करा',
      'settings': 'सेटिंग्स',
      'withdrawal_history': 'पैसे काढण्याचा इतिहास',
      'payment_settings': 'पेमेंट सेटिंग्स',
      'help_support': 'मदत आणि समर्थन',
      'insured': 'विमाधारक',
      'not_insured': 'विमा नाही',
      'get_gigbit_insurance': 'GigBit विमा घ्या',
      'insurance_opt_in_title': 'GigBit विमा सुरू करायचा?',
      'insurance_opt_in_body':
          'GigBit विम्यासाठी दर महिन्याला Rs 75 शुल्क आकारले जाईल. हे प्रत्येक महिन्याच्या 1 तारखेला आपोआप वजा होईल आणि विमा फीचर्स सुरू होतील.',
      'yes': 'हो',
      'no': 'नाही',
      'logout': 'लॉगआउट',
      'done': 'पूर्ण',
      'edit': 'संपादित करा',
      'enable_vehicle_rent': 'वाहन भाडे सक्षम करा',
      'wallet_balance': 'वॉलेट शिल्लक',
      'total_withdrawable_balance': 'एकूण काढण्यायोग्य शिल्लक',
      'withdraw_now': 'आता पैसे काढा',
      'withdraw_funds': 'रक्कम काढा',
      'amount': 'रक्कम',
      'total_earnings': 'एकूण कमाई',
      'total_withdrawn': 'एकूण पैसे काढले',
      'insurance_pool': 'विमा पूल',
      'transactions': 'व्यवहार',
      'trips': 'ट्रिप्स',
      'platform_earnings_breakdown': 'ब्रेकडाउन',
      'no_platform_data': 'सध्या प्लॅटफॉर्म डेटा नाही',
      'add_transaction': 'व्यवहार जोडा',
      'platform': 'प्लॅटफॉर्म',
      'save_transaction': 'सेव्ह करा',
      'add_expense': 'खर्च जोडा',
      'category': 'श्रेणी',
      'save_expense': 'खर्च सेव्ह करा',
      'platform_connections': 'प्लॅटफॉर्म कनेक्शन',
      'platform_name': 'प्लॅटफॉर्म नाव',
      'connect': 'कनेक्ट',
      'sync_amount': 'सिंक रक्कम',
      'sync_earning': 'कमाई सिंक',
      'total_contribution': 'एकूण योगदान',
      'submit_insurance_claim': 'विमा दावा सबमिट करा',
      'description': 'वर्णन',
      'submit_claim': 'दावा सबमिट',
      'recent_contributions': 'अलीकडील योगदान',
      'eligibility_score': 'पात्रता स्कोर',
      'recommended_limit': 'शिफारस मर्यादा',
      'loan_amount': 'कर्ज रक्कम',
      'apply_loan': 'कर्ज अर्ज',
      'subscription': 'सब्स्क्रिप्शन',
      'plans': 'प्लॅन्स',
      'active_plan': 'सक्रिय प्लॅन',
      'remaining': 'उर्वरित',
      'starter': 'स्टार्टर',
      'pro': 'प्रो',
      'power': 'पॉवर',
      'solo': 'सोलो',
      'duo': 'डुओ',
      'trio': 'ट्रायो',
      'unity': 'युनिटी',
      'subscription_plans': 'सब्स्क्रिप्शन प्लॅन्स',
      'expires': 'समाप्ती',
      'payment_method': 'पेमेंट पद्धत',
      'upi': 'UPI',
      'card': 'कार्ड',
      'net_banking': 'नेट बँकिंग',
      'pay_now': 'पे करा',
      'month': 'महिना',
      'up_to': 'पर्यंत',
      'platforms': 'प्लॅटफॉर्म',
      'subscription_required': 'सब्स्क्रिप्शन आवश्यक आहे',
      'required_to_continue': 'पुढे जाण्यासाठी',
      'plan_limit_reached': 'प्लॅन लिमिट पूर्ण झाली',
      'plan_slots_note':
          'तुम्ही फक्त आधी कनेक्ट केलेले प्लॅटफॉर्म पुन्हा कनेक्ट करू शकता.',
      'platform_limit': 'प्लॅटफॉर्म मर्यादा',
      'logged_in_as': 'लॉगिन वापरकर्ता',
      'your_information': 'तुमची माहिती',
      'other_information': 'इतर माहिती',
      'notifications': 'नोटिफिकेशन्स',
      'legal': 'कायदेशीर',
      'faqs': 'वारंवार विचारलेले प्रश्न',
      'raise_ticket': 'टिकिट उघडा',
      'terms_conditions': 'अटी व शर्ती',
      'accept_terms': 'मी अटी व शर्ती मान्य करतो/करते',
      'accept_terms_required': 'पुढे जाण्यासाठी अटी व शर्ती मान्य करा',
      'vehicle_rented': 'वाहन भाड्याने?',
      'gigbit_insurance': 'GigBit विमा?',
      'daily_fuel': 'दैनिक इंधन',
      'enter_daily_fuel': 'दैनिक इंधन खर्च भरा',
      'rent': 'भाडे',
      'enter_valid_rent': 'योग्य भाडे भरा',
      'daily': 'दैनिक',
      'weekly': 'साप्ताहिक',
      'monthly': 'मासिक',
      'yearly': 'वार्षिक',
      'privacy_policy': 'गोपनीयता धोरण',
      'full_name': 'पूर्ण नाव',
      'username': 'यूजरनेम',
      'enter_full_name': 'पूर्ण नाव टाका',
      'enter_valid_username':
          'यूजरनेम 3-24 अक्षरांचा असावा (a-z, 0-9, . किंवा _)',
      'new_password_min_8': 'पासवर्ड किमान 8 अक्षरांचा असावा',
      'update_profile': 'प्रोफाइल अपडेट',
      'change_email': 'ईमेल बदला',
      'new_email': 'नवीन ईमेल',
      'request_change': 'विनंती पाठवा',
      'change_password': 'पासवर्ड बदला',
      'password': 'पासवर्ड',
      'old_password': 'जुना पासवर्ड',
      'new_password': 'नवीन पासवर्ड',
      'update_password': 'पासवर्ड अपडेट',
      'create_account': 'खाते तयार करा',
      'login': 'लॉगिन',
      'please_wait': 'कृपया थांबा...',
      'forgot_password': 'पासवर्ड/यूजरनेम विसरलात?',
      'registered_username': 'नोंदणीकृत यूजरनेम',
      'need_account': 'खाते नाही? नोंदणी करा',
      'already_account': 'आधीच खाते आहे? लॉगिन करा',
      'create_your_account': 'तुमचे खाते तयार करा',
      'welcome_back': 'पुन्हा स्वागत',
      'secure_wallet': 'गिग वर्कर्ससाठी\nसुरक्षित वॉलेट',
      'track_earnings':
          'कमाई ट्रॅक करा, पैसे काढणे व्यवस्थापित करा आणि आर्थिक नियंत्रण ठेवा.',
      'integrate_gig_platforms': 'गिग प्लॅटफॉर्म जोडा',
      'connect_gig_platforms': 'प्लॅटफॉर्म कनेक्ट करा',
      'integration_hint':
          'प्रत्येक प्लॅटफॉर्मचा नोंदणीकृत मोबाइल नंबर द्या, OTP सत्यापित करा, मग डॅशबोर्डवर जा.',
      'continue_dashboard': 'डॅशबोर्डवर पुढे जा',
      'verified': 'सत्यापित',
      'connected': 'कनेक्टेड',
      'registered_mobile': 'नोंदणीकृत मोबाइल नंबर',
      'mobile_hint': 'उदा. 98XXXXXXXX',
      'verify_otp': 'OTP तपासा',
      'send_otp': 'OTP पाठवा',
      'send_otp_first': 'आधी OTP पाठवा',
      'enter_otp': 'OTP टाका',
      'cancel': 'रद्द',
      'update': 'अपडेट',
      'reset_password': 'पासवर्ड रीसेट',
      'registered_email': 'नोंदणीकृत ईमेल',
      'password_updated': 'पासवर्ड अपडेट झाला. कृपया लॉगिन करा.',
      'otp_generated': 'OTP तयार:',
      'otp_sent_to_email': 'OTP तुमच्या ईमेलवर पाठवला आहे.',
      'enter_valid_email': 'वैध ईमेल टाका',
      'otp_must_be_6_digits': 'OTP 6 अंकांचा असावा',
      'otp_verified_continue': 'OTP तपासला गेला. आता नोंदणी पूर्ण करा.',
      'dev_mode': '(डेव मोड)',
      'coming_soon': 'जल्द आ रहा है',
      'verify_one_platform': 'पुढे जाण्यासाठी किमान एक प्लॅटफॉर्म सत्यापित करा',
      'invalid_otp_for': 'चुकीचा OTP:',
      'verified_successfully': 'यशस्वी सत्यापन',
      'enter_valid_mobile': 'वैध नोंदणीकृत मोबाइल नंबर टाका',
      'delete_account_permanently': 'खाते हटवा',
      'delete_account_subtitle': 'एडमिन मंजुरी आवश्यक',
      'delete_account_reason': 'तुम्ही खाते का हटवू इच्छिता?',
      'delete_account_reason_hint': 'कारण निवडा',
      'delete_account_other_reason': 'इतर कारण',
      'delete_account_submit': 'विनंती पाठवा',
      'delete_account_submitted': 'विनंती एडमिन मंजुरीसाठी पाठवली',
      'reason_privacy': 'गोपनीयता चिंता',
      'reason_not_using': 'आता GigBit वापरत नाही',
      'reason_switching': 'दुसऱ्या अ‍ॅप/खात्यावर जात आहे',
      'reason_support': 'वाईट अनुभव / सपोर्ट समस्या',
      'reason_other': 'इतर',
    },
  };

  static String t(AppLanguage lang, String key) {
    return _v[lang]?[key] ?? _v[AppLanguage.en]![key] ?? key;
  }

  static AppLanguage next(AppLanguage current) {
    switch (current) {
      case AppLanguage.en:
        return AppLanguage.hi;
      case AppLanguage.hi:
        return AppLanguage.mr;
      case AppLanguage.mr:
        return AppLanguage.en;
    }
  }

  static String label(AppLanguage lang) => t(lang, 'lang_label');
}
